spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgrespw
    url: jdbc:postgresql://localhost:49154/postgres
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: create
    database: postgresql