spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: yhqiuizzazuvfa
    password: 3da359410627bdd52f2528dff4d567f8e61dbd1d669cde8ae09efbd5f8970640
    url: jdbc:postgresql://ec2-54-225-234-165.compute-1.amazonaws.com:5432/d8ff8dmm406lgk
  jpa:
    show-sql: true
    database: postgresql